title: Polly Yao
description: MS Student in Technology Innovation

baseurl: ""
url: "https://pollyyaooo.github.io/"

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Markdown
highlighter: rouge
markdown: kramdown

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
